# Generated by Django 3.2.9 on 2022-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('INTERN', 'intern'), ('EMP', 'employee'), ('SUP', 'supervisor'), ('NEW', 'new')], default='NEW', max_length=6),
        ),
    ]
